ROUTINE test

start(console=0)
    If console {
        Do {
            Do ##class(User.Scr).clearScreen()
            Write "Start"
            Write !
            Write !,"Settings Manager (1)"
            Write !,"input Setting (2)"
            Write !,"Exit (0)"
            Write !
            Set selection= ##class(User.Scr).input("Select")
            If selection=1 Do start^SettingsManager
            If selection=2 Set set=##class(User.Setting).%New(1) Do set.input()
        } While selection'=0
    }
    Quit
